# Generated by Django 4.0.6 on 2022-08-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='facebook_url',
            new_name='facebook_id',
        ),
    ]
